package com.kenzie.appserver.repositories.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Appointments")
public class AppointmentRecord {
    private String appointmentId;
    private String patientFirstName;
    private String patientLastName;
    private String providerName;
    private String appointmentDate;


    @DynamoDBHashKey(attributeName = "appointmentId")
    @DynamoDBAutoGeneratedKey
    public String getAppointmentId() {
        return appointmentId;
    }
    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    @DynamoDBAttribute(attributeName = "patientFirstName")
    public String getPatientFirstName() {
        return patientFirstName;
    }

    public void setPatientFirstName(String patientFirstName) {
        this.patientFirstName = patientFirstName;
    }

    @DynamoDBAttribute(attributeName = "patientLastName")
    public String getPatientLastName() {
        return patientLastName;
    }

    public void setPatientLastName(String patientLastName) {
        this.patientLastName = patientLastName;
    }

    @DynamoDBAttribute(attributeName = "providerName")
    public String getProviderName() {
        return providerName;
    }

    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    @DynamoDBAttribute(attributeName = "appointmentDate")
    public String getAppointmentDate() {
        return appointmentDate;
    }

    public void setAppointmentDate(String appointmentDate) {
        this.appointmentDate = appointmentDate;
    }
}
