package com.kenzie.appserver.repositories.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.util.Objects;

@DynamoDBTable(tableName = "Appointments")
public class AppointmentRecord {
    private String appointmentId;
    private String patientFirstName;
    private String patientLastName;
    private String providerName;
    private String gender;
    private String appointmentDate;
    private String appointmentTime;


    @DynamoDBHashKey(attributeName = "appointmentId")
    @DynamoDBAutoGeneratedKey
    public String getAppointmentId() {
        return appointmentId;
    }

    public void setAppointmentId(String appointmentId) {
        this.appointmentId = appointmentId;
    }

    @DynamoDBAttribute(attributeName = "patientFirstName")
    public String getPatientFirstName() {
        return patientFirstName;
    }

    public void setPatientFirstName(String patientFirstName) {
        this.patientFirstName = patientFirstName;
    }

    @DynamoDBAttribute(attributeName = "patientLastName")
    public String getPatientLastName() {
        return patientLastName;
    }

    public void setPatientLastName(String patientLastName) {
        this.patientLastName = patientLastName;
    }

    @DynamoDBAttribute(attributeName = "providerName")
    public String getProviderName() {
        return providerName;
    }

    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    @DynamoDBAttribute(attributeName = "gender")
    public String getGender() { return gender;
    }

    public void setGender(String gender) { this.gender = gender;}

    @DynamoDBAttribute(attributeName = "appointmentDate")
    public String getAppointmentDate() {
        return appointmentDate;
    }

    public void setAppointmentDate(String appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    @DynamoDBAttribute(attributeName = "appointmentTime")
    public String getAppointmentTime() {
        return appointmentTime;
    }

    public void setAppointmentTime(String appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AppointmentRecord)) return false;
        AppointmentRecord record = (AppointmentRecord) o;
        return Objects.equals(appointmentId, record.appointmentId) && Objects.equals(patientFirstName, record.patientFirstName) && Objects.equals(patientLastName, record.patientLastName) && Objects.equals(providerName, record.providerName) &&
                Objects.equals(gender, record.gender) && Objects.equals(appointmentDate, record.appointmentDate) && Objects.equals(appointmentTime, record.appointmentTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(appointmentId, patientFirstName, patientLastName, providerName, gender, appointmentDate, appointmentTime);
    }
}
